// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bread: typeof import('./src/components/bread/index.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    Carousel: typeof import('./src/components/carousel/index.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/index.vue')['default']
    City: typeof import('./src/components/city/index.vue')['default']
    Confirm: typeof import('./src/components/confirm/confirm.vue')['default']
    Item: typeof import('./src/components/bread/item.vue')['default']
    Message: typeof import('./src/components/message/message.vue')['default']
    More: typeof import('./src/components/more/index.vue')['default']
    Numbox: typeof import('./src/components/numbox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/skeleton/index.vue')['default']
  }
}
